version: 1
snapshot:
  widths: [
    # Reference: https:#mediag.com/blog/popular-screen-resolutions-designing-for-all/
    320,   # xs iPhone 5/SE
    375,   # xs iPhone 6/7/8
    # -- NOT ACTIVATING -- 390,   # xs iPhone 12/Pro
    # -- NOT ACTIVATING -- 414,   # xs iPhone 6/7/8 Plus
    428,   # xs iPhone 12 Pro Max
    # -- NOT ACTIVATING -- 4642,   # sm iPhone 12 Pro 1284x2778
    768,   # md iPad 6/7, Pro4
    834,   # md iPad Air3, Pro3
    1024,  # lg iPad Pro
    1280,  # xl Middle Resolution MacBook Pro 15in 
    1920,  # xl Largest Resolution MacBook Pro 15in
    # -- NOT ACTIVATING -- 42560,  # xl DELL U2719DC 27inch
    3440,  # xl Samsung 34-Inch SJ55W Ultrawide Gaming Monitor 
  ]
static-snapshots:
  snapshot-files: '*.html'
  ignore-files: './node_modules/**/*.*'