name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: bundle install
      - name: Percy Test
        uses: percy/snapshot-action@v0.1.2
        with:
          build-directory: "/"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
